#!/usr/bin/env node

const chalk = require('chalk')
const Crypto = require('./crypto')
const yargs = require('yargs')

const argv = yargs
  .command('* <data>', 'encrypt or decrypt <data>', yargs => yargs
    .options({
      d: {
        alias: 'decode',
        describe: 'decode data',
        type: 'boolean'
      },
      k: {
        alias: 'key',
        demandOption: true,
        describe: 'master key',
        type: 'string'
      }
    })
  )
  .help()
  .argv

const crypto = new Crypto(argv.k)

try {
  if (argv.d) {
    console.log(crypto.decrypt(argv.data))
  }
  else console.log(crypto.encrypt(argv.data))
}
catch(e) {
  console.log(chalk.red(`Error: ${e.message}`))
}


